import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import  Header from "@/components/Header"  
import ActiveSectionContent from '@/context/ActiveSectionContent'
import Footer from '@/components/Footer'
import ThemeSwitch from '@/components/ThemeSwitch'
import ThemeContextProvider from '@/context/ThemeContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='!scroll-smooth'>
      <body className={`${inter.className} bg-gray-50 text-gray-950 relative pt-28 sm:pt-36 dark:bg-gray-950 dark:text-gray-50 dark:text-opacity-90`}>
        <div className='bg-[#fbe2e3] absolute top-[-6rem] right-[11rem] h-[32.25rem] w-[32.25rem] rounded-full blur-[10rem] sm:w-[68.75rem]  -z-10'/>
        <div className='bg-[#dbd7fb] absolute top-[-1rem] left-[-35rem] h-[32.25rem] w-[50rem] rounded-full blur-[10rem] sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem]  -z-10'/>
        <ThemeContextProvider>
      <ActiveSectionContent>
        <Header/>
        {children}
        <Footer/>
        <ThemeSwitch/>
      </ActiveSectionContent>
        </ThemeContextProvider>
        </body>
    </html>
  )
}
